### ISSUE TITLE
Feature Request: support space before/after =

### ISSUE THREAD

**Issue by aletheia7** [wgwoods/vim-systemd-syntax#2]
Syntax highlighting works great for key/value pairs such as:
```
Description=Expense
```
Syntax highlighting does not work for lines like:
```
Description = Expense
```
Could you enable the script to support spaces before/after the "="?

**Comment by wgwoods** [comment]
Aw blerg. Yeah, this is technically possible. At the moment, I think the syntax allows whitespace after the `=`, so it should work fine for lines like:
```
Description= Expense
```
Unfortunately, because of the way the syntax file is written, fixing this to allow whitespace before the `=` means hand-editing all the regexes that end with `/[...]=/` to be `/[...]\s*=/`. ("`=/`" shows up in a lot of different places in that file, so this isn't just a simple regex or one-line change.. so it's gonna take me a bit of effort.)

In the meantime, fixing a service file to remove spaces before `=` is pretty simple:
```vim
:%s/^\(\w\+\)\s\+=/\1=/
```
