### ISSUE TITLE
still relevant these days

### ISSUE THREAD

**Issue by laoshaw** [wgwoods/vim-systemd-syntax#8]
looks like vim supports systemd syntax out of box these days, is this plugin still relevant?

**Comment by wgwoods** [comment]
Kinda depends on what you find relevant. The builtin vim [`syntax/systemd.vim`](https://github.com/vim/vim/blob/v9.1.0538/runtime/syntax/systemd.vim) does basic syntax highlighting based on the structure of the file, but it doesn't have any actual knowledge of systemd unit files. It just assumes they're formatted like `dosini` files. Which they are.

This plugin knows enough about systemd unit file syntax to highlight known directives and various systemd-specific data types - durations, booleans, unit names, virtualization types, architectures, etc. It'll also flag syntax errors, like using a non-boolean argument to a directive that takes a boolean. And so on. It's a good bit smarter than the vim builtin syntax plugin.

On the other hand, it is a bit out-of-date. I haven't updated it in a couple years, so it's almost certainly missing some stuff that's been added to systemd since I last touched it.

So. If by "relevant" you mean "still useful" or "does more than the builtin vim plugin", then: yeah, sure!

If you mean "under active development" or "guaranteed to be up-to-date with the latest systemd changes": no. I'll still happily take patches, and I may even update things once every few systemd releases, but I'm not actively working on this right now.
